@url_dev = http://localhost:8080
@url_dev_v1 = {{url_dev}}/v1/api/discount

### Section 21: create discount, appliesTo all type 
POST  {{url_dev_v1}}/
Content-Type: application/json
x-api-key: CAQca9dFGf5R
Authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhdXRoMCIsImV4cCI6MTcwMzY2MjU2MiwidHlwZSI6ImFjY2Vzc1Rva2VuIiwidXNlcklkIjoiNjUxODQ3ZWUzYjgzMjcwODcyMmEwMmQ4IiwiZW1haWwiOiJzaG9wZGV2XzFAZ21haWwuY29tIiwidGltZXN0YW1wIjoxNjk3NjYyNTYyMDE0fQ.JefTYa3Z7z5hoDbBcopmTIOIJOeCTPMR2ivsRceW4E91ZbvNjdviqDxO09a2O6js5DsGxbTMgwlYxqXnxnqoGJPtGANtN0h2m5pmmEs1PvI_Zx8g_7x5pNCpYq1nK2TSPCQMlbrzDEIpJlYmXc90nUJcCH3h-hVtwkfhAn6B-_s3HVftmKo2PUvbw55mNdqu3tnVmj-_5MleuyWBjgYkDID882aEgXO2pEE7a6tXYPl4gmlwyPwgSqiM-JWja5VDdIIZQE0ZhTFeSpSlSM548bTHj3zr1pV80Hx3CTuoneJORMKZ6oyFu9mlMuyNsVUhW6efFO2-2KoFBtdISHCfBA

{

        "discountName": "shoppe halloween discount",
        "discountDescription" : "discount description",
        "discountType" : "fixed_amount",
        "discountValue": 10000,
        "discountCode": "SHOPPE_HALLOWEEN",
        "discountStartDate": "2023-12-20 00:01:40",
        "discountEndDate" : "2023-12-25T01:01:10",
        "discountMaxUses": 1000,
        "discountMaxUsesPerUser": 5,
        "discountMinOrderValue" : 200000,
        "isActive" : false,
        "discountAppliesTo" : "all"
}

### Section 21: create discount, appliesTo specific type 
POST  {{url_dev_v1}}/
Content-Type: application/json
x-api-key: CAQca9dFGf5R
Authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhdXRoMCIsImV4cCI6MTcwMzY2MjU2MiwidHlwZSI6ImFjY2Vzc1Rva2VuIiwidXNlcklkIjoiNjUxODQ3ZWUzYjgzMjcwODcyMmEwMmQ4IiwiZW1haWwiOiJzaG9wZGV2XzFAZ21haWwuY29tIiwidGltZXN0YW1wIjoxNjk3NjYyNTYyMDE0fQ.JefTYa3Z7z5hoDbBcopmTIOIJOeCTPMR2ivsRceW4E91ZbvNjdviqDxO09a2O6js5DsGxbTMgwlYxqXnxnqoGJPtGANtN0h2m5pmmEs1PvI_Zx8g_7x5pNCpYq1nK2TSPCQMlbrzDEIpJlYmXc90nUJcCH3h-hVtwkfhAn6B-_s3HVftmKo2PUvbw55mNdqu3tnVmj-_5MleuyWBjgYkDID882aEgXO2pEE7a6tXYPl4gmlwyPwgSqiM-JWja5VDdIIZQE0ZhTFeSpSlSM548bTHj3zr1pV80Hx3CTuoneJORMKZ6oyFu9mlMuyNsVUhW6efFO2-2KoFBtdISHCfBA

{

        "discountName": "teacher discount",
        "discountDescription" : "discount description",
        "discountType" : "fixed_amount",
        "discountValue": 10000,
        "discountCode": "SHOPPE_TEACHER",
        "discountStartDate": "2023-12-20 00:01:40",
        "discountEndDate" : "2023-12-25T01:01:10",
        "discountMaxUses": 100,
        "discountMaxUsesPerUser": 3,
        "discountMinOrderValue" : 20000,
        "isActive" : false,
        "discountAppliesTo" : "specific",
        "discountProductIds": ["6537d0fa932f3a1f4f1550be", "6537d12a932f3a1f4f1550bf"]
}