@url_dev = http://localhost:8080
@url_dev_v1 = {{url_dev}}/v1/api

### section 3 _ 1
GET {{url_dev}}/section3/insert?name=nhat

### section 3 _ 2
GET {{url_dev}}/section3/insert?name=lan

### section 5.1 _ signup
POST {{url_dev}}/v1/api/shop/signup
Content-Type: application/json
x-api-key: CAQca9dFGf5R

{
    "name": "shop_2", 
    "email": "shopdev_2@gmail.com",
    "password" : "password",
    "status": "ACTIVE",
    "roles" : ["SHOP", "ADMIN"]

}

### section 5_1: get shop by name 
GET {{url_dev_v1}}/shop/get-shop?name=shop_1


### section 5_1: get shop by name. Case name is empty
GET {{url_dev_v1}}/shop/get-shop?name=

### section 5_1. login
POST {{url_dev_v1}}/shop/login
Content-Type: application/json
x-api-key: CAQca9dFGf5R

{
    "email": "shopdev_1@gmail.com",
    "password" : "password"
}


### section 5_3, verify token 
GET {{url_dev_v1}}/shop/verifyToken?token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhdXRoMCIsImV4cCI6MTY5NzAwMzc0NiwidHlwZSI6ImFjY2Vzc1Rva2VuIiwidXNlcklkIjoiNjUxODQ3ZWUzYjgzMjcwODcyMmEwMmQ4IiwiZW1haWwiOiJzaG9wZGV2XzFAZ21haWwuY29tIiwidGltZXN0YW1wIjoxNjk3MDAzNDQ2NzIyfQ.l598-HgWRulx26LvTIPFUMCZgsBH440KAtwthVzvEFDOl8WFlRo2RbatsbyePB-umnYqt0wbGEQs0q4UEgO4YDwXXZ30qLpi2YxgouihLrkQbcfNm58PAsKMShVqslzDv9GvrYnXsO4wqWV7Va6kgg7dGUKwjXnZeM7d3TBRmoHAWFqffJxaS8UzsMfIYGTZkbjTKP_OKCfwxgfNMNRdy_3M0HPRb1-X2ZgI8_Kh_FLd1YtLBXt4oFw8Ys6r7cyYKL-5VHzp4pJ1yWfkP-o8Oyluz1fh8OlAFDDWnr8RYMHqYbiKX2NeF1j5-CLgXmuyA8GIUY9fj5GzlLcs-Y0n9w
x-api-key: CAQca9dFGf5R

### Section 6. create api_key 
GET {{url_dev_v1}}/shop/create-api-key

### section 10. logout
POST {{url_dev_v1}}/shop/logout
Content-Type: application/json
x-api-key: CAQca9dFGf5R
Authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhdXRoMCIsImV4cCI6MTY5NzAwMzc0NiwidHlwZSI6ImFjY2Vzc1Rva2VuIiwidXNlcklkIjoiNjUxODQ3ZWUzYjgzMjcwODcyMmEwMmQ4IiwiZW1haWwiOiJzaG9wZGV2XzFAZ21haWwuY29tIiwidGltZXN0YW1wIjoxNjk3MDAzNDQ2NzIyfQ.l598-HgWRulx26LvTIPFUMCZgsBH440KAtwthVzvEFDOl8WFlRo2RbatsbyePB-umnYqt0wbGEQs0q4UEgO4YDwXXZ30qLpi2YxgouihLrkQbcfNm58PAsKMShVqslzDv9GvrYnXsO4wqWV7Va6kgg7dGUKwjXnZeM7d3TBRmoHAWFqffJxaS8UzsMfIYGTZkbjTKP_OKCfwxgfNMNRdy_3M0HPRb1-X2ZgI8_Kh_FLd1YtLBXt4oFw8Ys6r7cyYKL-5VHzp4pJ1yWfkP-o8Oyluz1fh8OlAFDDWnr8RYMHqYbiKX2NeF1j5-CLgXmuyA8GIUY9fj5GzlLcs-Y0n9w

