@url_dev = http://localhost:8080

### section 3 _ 1
GET {{url_dev}}/section3/insert?name=nhat

### section 3 _ 2
GET {{url_dev}}/section3/insert?name=lan

### section 5.1
POST {{url_dev}}/v1/api/shop/signup
Content-Type: application/json

{
    "name": "shop_1", 
    "email": "shopdev_1@gmail.com",
    "password" : "password",
    "status": "ACTIVE",
    "roles" : ["SHOP", "ADMIN"]

}